version: '3'

services:
  # web:
  #   image: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - app
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/app
    environment:
      - PORT=3000
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - "5432:5432"